### ISSUE TITLE
Add a Command Line Calculator function

### ISSUE THREAD

**Issue by rahulkumaran** [rahulkumaran/Utlyz-CLI#10]
add a file calc.py to the Utilities folder where the function must perform atleast the 5 basic arithmetic operations. Make sure it works while on virtual environment.
for eg: If you say calc --add "2 + 5" or just calc --add, the function must perform the add operation.
The way you choose to implement it is left to you

**Comment by namantw** [comment]
@rahulkumaran Can I work on this?

**Comment by rahulkumaran** [comment]
Sure! I'll assign this issue to you

**Comment by namantw** [comment]
Okay, thanks.

**Comment by namantw** [comment]
![image](https://user-images.githubusercontent.com/31323328/34766870-11803c90-f61c-11e7-95ba-8a25c0a8038f.png)
PR is on its way :)
