### ISSUE TITLE
Refine the code in news.py

### ISSUE THREAD

**Issue by rahulkumaran** [rahulkumaran/Utlyz-CLI#11]
In the file news.py, there are 2 bugs.
(1) There's this "Continue Reading" which gets printed. Remove that part but everything else should remain the same.
(2) Print "->" only when there is some news bulletin which gets printed. Currently, if you observe, it actually gets printed on lines where there's no news bulletin.

Rectify these 2 bugs

**Comment by Jigar3** [comment]
while running news --trending I get the following error
`Traceback (most recent call last):
  File "/home/jsc39/opencode/Utlyz-CLI/env1/bin/news", line 11, in <module>
    load_entry_point('utlyz', 'console_scripts', 'news')()
TypeError: cli() takes exactly 1 argument (0 given)
`
Any idea what causes this @rahulkumaran

**Comment by rahulkumaran** [comment]
before the click options add the '@' symbol.
like @click.command()
@click.option(----)

The symbol is missing! That's the only problem! :) 

I'll make the changes to the code right away though! Thanks for letting me know btw :)

**Comment by rahulkumaran** [comment]
@Jigar3 https://github.com/rahulkumaran/Utlyz-CLI/blob/master/Utilities/news.py 
check the updated code here! Update the code on your local repo as well :)

**Comment by Jigar3** [comment]
Ya I would like to work on it

**Comment by rahulkumaran** [comment]
Great! This issue has been assigned to you :)
