### ISSUE TITLE
Beautify README.md

### ISSUE THREAD

**Issue by rahulkumaran** [rahulkumaran/Utlyz-CLI#13]
Currently, README.md has all the info. Your job is just to make it look more attractive.

**Comment by namantw** [comment]
@rahulkumaran I want to work on this and should I add another rookie issue for updating Readme.md with `calc` commands that were added by me?

**Comment by Anupam-dagar** [comment]
@namantw update that it in this itself if it has to be updated

**Comment by rahulkumaran** [comment]
@namantw , nope! you need not create a new issue for that. As @Anupam-dagar  said, while beautifying the README.md file, just make sure you add the commands related to calc also.

**Comment by namantw** [comment]
okay I am working on it, sorry for being a bit too late :)

**Comment by namantw** [comment]
@rahulkumaran please review
