### ISSUE TITLE
create a proper industry standary file structure for this particular project

### ISSUE THREAD

**Issue by rahulkumaran** [rahulkumaran/Utlyz-CLI#20]
Create an industry standard file structure with folders such as build,docs,app and others that are necessary

app folder should contain all the .py files except setup.py
build must contain setup.py and prep.sh (please rename it to build.sh)
docs must contain all .md files except LICENSE.md and README.md

Each of these docs must be added with a README.md explaining what that particular folder contains.

I except you guys to add all those important folders which are required! The 3 mentioned above are compulsory apart from which I expect you guys to have atleast 1 more file!
Make sure no commits are made to the programs. You're allowed to modify only file names basically! 

Contact me for any doubt :smile:

**Comment by Jigar3** [comment]
I would like to take up this issue

**Comment by rahulkumaran** [comment]
Great! This has been assigned to you! Follow all the instructions mentioned above carefully! And before working on any other issue, work on this 1st because the otherwise there might be merge conflicts which arise!

I'll wait for you to update the folder before accepting other PRs! So try to make it asap

**Comment by rahulkumaran** [comment]
Great! This has been assigned to you! Follow all the instructions mentioned above carefully! And before working on any other issue, work on this 1st because the otherwise there might be merge conflicts which arise!

I'll wait for you to update the folder before accepting other PRs! So try to make it asap

**Comment by rahulkumaran** [comment]
Also, don't make the changes directly on your master! Create a new branch and make the changes on that!

**Comment by Jigar3** [comment]
After shuffling all the files I tried to run the program but then it gives import error

**Comment by rahulkumaran** [comment]
Can you send me a screenshot of the error?

**Comment by Jigar3** [comment]
![screenshot from 2018-01-11 13-38-05](https://user-images.githubusercontent.com/32068121/34814701-a454e0da-f6d4-11e7-9425-f90ac5688dfd.png)

**Comment by rahulkumaran** [comment]
Can you also send a screenshot of the directories you have under Utlyz-CLI

**Comment by Jigar3** [comment]
![screenshot from 2018-01-11 13-44-54](https://user-images.githubusercontent.com/32068121/34814973-9c6ccb98-f6d5-11e7-88cc-823fccb1924b.png)
![screenshot from 2018-01-11 13-45-11](https://user-images.githubusercontent.com/32068121/34814978-a0543d22-f6d5-11e7-8519-4928d2f60973.png)

**Comment by rahulkumaran** [comment]
You tried running cricbuzz --help in Utlyz-CLI directory! You're currently in the Utlyz-CLI directory! Type "cd apps" and go into the "apps" directory and type cricbuzz--help after you're in the apps directory! It should work hopefully ! Let me know after you try

**Comment by rahulkumaran** [comment]
Aaaahh! Okay I get it! Do one thing! In the build directory keep only build.sh.
And keep setup.py in the apps directory itself.
I'll be making a small change to shellscript now.
Update your the file in your local repo too! @Jigar3

**Comment by rahulkumaran** [comment]
actually ykw? Instead me making the change now, you make it on your local repo! Because if I make it now, it'll screw up the installation process if anyone else downloads it now.
I'll tel you the changes that are to be made.
Wherever you have the "pip install --editable ." change it to "pip install --editable apps/"

You'll have it in 2 locations. Change it in both locations.

![screenshot from 2018-01-11 19-23-42](https://user-images.githubusercontent.com/26206171/34828869-f5b9e918-f704-11e7-9802-47c3f80a3d42.png)
