### ISSUE TITLE
Update the README.md and INSTALL.md

### ISSUE THREAD

**Issue by Jigar3** [rahulkumaran/Utlyz-CLI#25]
As there has been changes made in the structure of the application, these files need to get updated

Would you like to take this issue?
Yes

**Comment by rahulkumaran** [comment]
Since the file restructuring issue was taken care by you, it was expected that you take care of this then itself. Anyway, you can send a PR directly :)

**Comment by Jigar3** [comment]
I was thinking that you can add this as an issue with a label first-timers-only so people new to opensource development could make their first PR.
What do u think? @rahulkumaran

**Comment by rahulkumaran** [comment]
cool! thanks for your suggestion :) just opened up an issue related to that :)
