### ISSUE TITLE
Add feature to read out news bulletins in news.py

### ISSUE THREAD

**Issue by rahulkumaran** [rahulkumaran/Utlyz-CLI#26]
Currently, the news bulletins are just displayed in the CLI! It'll be great if someone can integrate a voice feature which reads out the bulletins too :smile:

**Comment by Jigar3** [comment]
I want to take up this issue
Can you suggest some modules that can be useful

**Comment by rahulkumaran** [comment]
This has been assigned to you! @Jigar3

Well, if I suggest anything now, you'll lose the fun of doing it! Try it! Look it up on the net and let me know! If you still don't get it, I'll help you out ! It's pretty easy though!

**Comment by rahulkumaran** [comment]
By help I mean I can suggest a few modules which you can use!

**Comment by Jigar3** [comment]
Can you suggest some ?
