### ISSUE TITLE
update INSTALL.md under docs folder

### ISSUE THREAD

**Issue by rahulkumaran** [rahulkumaran/Utlyz-CLI#29]
Currently, this CLI app supports around 7-8 features but the INSTALL.md has info regarding 5 only.
Please add the missing features in that file and also make any other changes that are necessary!

**Comment by justnealpatel** [comment]
@rahulkumaran I would be willing to complete this issue, as it will be my first contribution.

**Comment by rahulkumaran** [comment]
Great! Go ahead @justnealpatel
