### ISSUE TITLE
Add CONTRIBUTIONS.md

### ISSUE THREAD

**Issue by rahulkumaran** [rahulkumaran/Utlyz-CLI#9]
Since there's no CONTRIBUTIONS.md in place in this repository, beginners can start off with writing a CONTRIBUTING.md

Once this issue is assigned, I'll be briefing the assignee about the points that must be added to the file.

**Comment by Jigar3** [comment]
I would like to work on this issue @rahulkumaran

**Comment by rahulkumaran** [comment]
Sure! You can work on this!

**Comment by Jigar3** [comment]
Can you brief about the points to be added in the file

**Comment by rahulkumaran** [comment]
before sending a PR, make sure issue is assigned to you
If not, wait for the issue to be assigned to you.
If you have a nice idea which you would want to implement, raise the issue 1st and describe in short why you want the implement that(2-3 lines). If it's convincing, the issue will be assigned to you.

After issue assigned :- 
1) the master of forked repo shouldnt be ahead in terms of commits as compared to original master repo.
2) create a new branch and make changes on the new branch. dont directly edit master repo.
3) make sure every issue you work on is done on a different branch.
4) only one file per PR will be merged. If unnecesary commits exist, it wont be merged.
5) Comments are a must. add as many as possible.

**Comment by rahulkumaran** [comment]
@Jigar3 , those aren't really elaborate. Try making it as elaborate as possible. You can go through [link](https://github.com/rahulkumaran/Algorithms/blob/catalan/CONTRIBUTING.md) to get an idea of how to proceed.
Please do no add numbers. Instead add bullets.
And make sure it's not exactly the same as that link. Just use that link for reference.

All the best

**Comment by rahulkumaran** [comment]
Also, rename the to CONTRIBUTING.md and not CONTRIBUTIONS.md
